# Generated by Django 4.1.7 on 2024-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=122)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=122)),
                ("content", models.TextField()),
            ],
        ),
    ]
